# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Wilen's Blog
subtitle: 寄蜉蝣于天地，渺沧海之一粟。
description: 个人笔记
keywords: 大数据 数学 Python R语言
author: Wilen Wu
language: zh-CN       # 网站采用语言，与<theme>/languages/zh-CN.yml下的文件名对应
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://wilenwu.gitee.io
root: /                        # 网站的根目录
# 文章永久链接的形成模版。每一篇文章都有唯一的url。
permalink: posts/:abbrlink/    # posts/:title/
permalink_defaults:            # 文章永久链接中，各部分的默认值。
  lang: en
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source           # 网站中源文件
public_dir: public           # 生成的静态网站的目录
tag_dir: tags                # 标签页所在的文件夹 
archive_dir: archives        # 文档页所在的文件夹
category_dir: categories     # 类别页所在的文件夹
code_dir: downloads/code     # 代码页所在的文件夹(根目录 
i18n_dir: :lang              # 国际语言所在的文件夹
skip_render:                 # 忽略文档(根目录 source_dir/)，不做改动地输出到 public 目录
  - "docs/**"
  - "_drafts/**"
  - "custom_scripts/**"


# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # 首字母大写
external_link: # 外链设置
  enable: true # Open external links in new tab
  field: site # Apply to the whole site|post
  exclude: ''
filename_case: 1  # 把文件名称转换为小写(1)、大写(2)或不变(0)
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true   
  line_number: false 
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false  
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''              # 主页所在路径，默认为''
  per_page: 10
  order_by: -date      # 文章（Post类型）排序属性，`-`为降序

# Category & Tag
default_category: uncategorized      # 对文档的默认分类
category_map:    # 对文档中的分类字段进行映射。建立分类文件夹时采用映射后的字符串 
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10            # 主页/分类/标签/存档等类型索引页包含文章数量
pagination_dir: page    # 分页所在文件夹 

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:  # Hexo 会忽略这些文件和目录
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly 

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repo: git@github.com:WilenWu/wilenwu.github.io.git
    branch: master
  - type: git
    repo: git@gitee.com:WilenWu/wilenwu.git
    branch: master
  - type: baidu_url_submitter

# @upupming/hexo-renderer-markdown-it-plus
markdown_it_plus:
  plugins:
    - plugin:
      name: '@neilsustc/markdown-it-katex'
      enable: true
      options:
        strict: false

# 激活leancloud插件
leancloud_counter_security: 
  enable_sync: true
  app_id: uVMHtcFR2bEYRTuPIjJUT6b-MdYXbMMI 
  app_key: 6EzBICTWxLbjiGsbNAa8Fv2s
  server_url: https://leancloud.cn # Required for apps from CN region, e.g. https://leancloud.cn
  username: 597379201@qq.com # Will be asked while deploying if is left blank
  password: Wu31415926 # Recommmended to be left blank. Will be asked while deploying if is left blank

# 配置 hexo-generator-search
search: 
  path: search.xml
  field: post
  content: true
  format: html

# 配置音乐插件
aplayer:
  asset_inject: false                            # 自动插入 Aplayer.js 与 Meting.js 资源脚本, 默认开启
  # script_dir: some/place                        # Public 目录下脚本目录路径，默认: 'assets/js'
  # style_dir: some/place                         # Public 目录下样式目录路径，默认: 'assets/css'
  # cdn: http://xxx/aplayer.min.js                # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
  # style_cdn: http://xxx/aplayer.min.css         # 引用 APlayer.css 外部 CDN 地址 (默认不开启)
  meting: true                                  # MetingJS 支持
  # meting_api: http://xxx/api.php                # 自定义 Meting API 地址
  # meting_cdn: http://xxx/Meing.min.js           # 引用 Meting.js 外部 CDN 地址 (默认不开启)
  # externalLink: http://xxx/aplayer.min.js       # 老版本参数，功能与参数 cdn 相同

# RSS 配置
feed: 
  enable: true
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

# 有效地加强网站SEO和防止权重流失
nofollow: 
  enable: true
  field: site
  exclude:
    #- 'exclude1.com'
    #- 'exclude2.com'

# 生成sitemap的插件
sitemap: 
  path: sitemap.xml

baidusitemap:
  path: baidusitemap.xml


# 主动推送百度，被百度收录
baidu_url_submit:
  count: 200                        # 提交最新的200个链接
  # site=https://wilenwu.github.io&token=P8wBelFwcBp0yS8z
  host: wilenwu.gitee.io            # 在百度站长平台中注册的域名
  token: P8wBelFwcBp0yS8z           # 秘钥，百度站长平台 > 普通收录 > 接口调用地址中token字段
  path: baidu_urls.txt              # 文本文档的地址， 新链接会保存在此文本文档里，不用改


# abbrlink config
abbrlink:
  alg: crc32      #support crc16(default) and crc32
  rep: hex        #support dec(default) and hex
  drafts: false   #(true)Process draft,(false)Do not process draft. false(default) 
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
     enable: true  #true(default)
     depth:        #3(default)
     over_write: false 
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink.

# 统计图表，支持发布文章统计、发布日历、Top标签统计、分类统计、分类雷达。
# see https://www.npmjs.com/package/hexo-butterfly-charts
charts:
  enable: true # 是否启用功能
  postsChart:
    title:  # 设置文章发布统计的标题，默认为空
    interval: 0 # 横坐标间隔
  tagsChart:
    title: Top 10 标签统计 # 设置标签统计的标题，默认为空
    interval: 0 # 横坐标间隔
  postsCalendar_Title: 文章发布日历 # 设置发布日历的标题，默认为空
  categoriesChart_Title: 文章分类统计 # 设置分类统计的标题，默认为空
  categoriesRadar_Title: # 设置分类雷达的标题，默认为空

# tag-plugins-plus
# see https://akilar.top/posts/615e2dec/
tag_plugins:
  enable: true # 开关
  priority: 5 #过滤器优先权
  issues: false #issues标签依赖注入开关
  link:
    placeholder: /img/link.png #link_card标签默认的图标图片
  CDN:
    anima: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/font-awesome-animation.min.css #动画标签anima的依赖
    jquery: https://npm.elemecdn.com/jquery@latest/dist/jquery.min.js #issues标签依赖
    issues: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/issues.js #issues标签依赖
    iconfont: //at.alicdn.com/t/font_2032782_8d5kxvn09md.js #参看https://akilar.top/posts/d2ebecef/
    carousel: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/assets/carousel-touch.js
    tag_plugins_css: https://npm.elemecdn.com/hexo-butterfly-tag-plugins-plus@latest/lib/tag_plugins.css

# hexo-butterfly-swiper
# see https://akilar.top/posts/8e1264d1/
swiper:
  enable: true # 开关
  priority: 6 #过滤器优先权
  enable_page: / # 应用页面
  timemode: date #date/updated
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  default_descr: 再怎么看我也不知道怎么描述它的啦！
  swiper_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.css #swiper css依赖
  swiper_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper.min.js #swiper js依赖
  custom_css: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiperstyle.css # 适配主题样式补丁
  custom_js: https://npm.elemecdn.com/hexo-butterfly-swiper/lib/swiper_init.js # swiper初始化方法

# hexo-filter-gitcalendar
# see https://akilar.top/posts/1f9c68c9/
gitcalendar:
  enable: true # 开关
  priority: 5 #过滤器优先权
  enable_page: / # 应用页面
  # butterfly挂载容器
  layout: # 挂载容器类型
    type: id
    name: recent-posts
    index: 0
  # volantis挂载容器
  # layout:
  #   type: class
  #   name: l_main
  #   index: 0
  # matery挂载容器
  # layout:
  #   type: id
  #   name: indexCard
  #   index: 0
  # mengd挂载容器
  # layout:
  #   type: class
  #   name: content
  #   index: 0
  user: WilenWu #git用户名
  apiurl: 'https://gitcalendar.akilar.top'
  minheight:
    pc: 280px #桌面端最小高度
    mibile: 0px #移动端最小高度
  # color: "['#e4dfd7', '#f9f4dc', '#f7e8aa', '#f7e8aa', '#f8df72', '#fcd217', '#fcc515', '#f28e16', '#fb8b05', '#d85916', '#f43e06']" #橘黄色调
  # color: "['#ebedf0', '#fdcdec', '#fc9bd9', '#fa6ac5', '#f838b2', '#f5089f', '#c4067e', '#92055e', '#540336', '#48022f', '#30021f']" #浅紫色调
  color: "['#ebedf0', '#f0fff4', '#dcffe4', '#bef5cb', '#85e89d', '#34d058', '#28a745', '#22863a', '#176f2c', '#165c26', '#144620']" #翠绿色调
  # color: "['#ebedf0', '#f1f8ff', '#dbedff', '#c8e1ff', '#79b8ff', '#2188ff', '#0366d6', '#005cc5', '#044289', '#032f62', '#05264c']" #天青色调
  container: .recent-post-item(style='width:100%;height:auto;padding:10px;') #父元素容器，需要使用pug语法
  gitcalendar_css: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.css
  gitcalendar_js: https://npm.elemecdn.com/hexo-filter-gitcalendar/lib/gitcalendar.js